name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt -r requirements.txt

      - name: Run model tests
        run: |
          cd tests
          python -m pytest -q model/test_model.py

      - name: Run API tests
        run: |
          cd tests
          python -m pytest -q api/test_api.py